### ISSUE TITLE
"doesn't support firewall" popup in the Qubes Manager

### ISSUE THREAD

**Issue by hannesm** [mirage/qubes-mirage-firewall#104]
@marmarek replied how to avoid his popup:

>  What does the firewall need to do to announce this capability to the system?

Ideally, support this: https://dev.qubes-os.org/projects/core-admin/en/latest/qubes-features.html

In short: when running in a TemplateVM, at startup write to qubesdb `/features-request/qubes-firewall` with value 1, then call `qubes.Features.Request` qrexec service to dom0 (nothing specific to be send, just call the service).

A manual workaround: in dom0 call `qvm-features <vmname> qubes-firewall 1`

**Comment by xaki23** [comment]
the official docs/vmspec after #116 is merged have the "workaround". (and it seems to be working)

from my POV having this as a configurable feature is better than mfw force-setting it at runtime.

**Comment by hannesm** [comment]
Ok,thanks for verifying. Closing this issue.
