### ISSUE TITLE
hostname dsthost not working

### ISSUE THREAD

**Issue by rootkit-ty** [mirage/qubes-mirage-firewall#106]
It seems that the default sys-firewall supports hostnames for appvm firewall configs.
The same cannot be said for mirage, as adding a hostname to a dsthost yeilds no changes to network connectivity.

It's fairly easy to reproduce, simply create an appvm with a hostname firewall rule, and switch between default sys-firewall and mirage-firewall and notice how mirage-firewall doesn't respect those rules.

**Comment by linse** [comment]
DNS resolution in firewall rules is supported in the firewall now.
How do you reproduce your problem step by step, and what's the error output you see?

**Comment by rootkit-ty** [comment]
It seems I didn't test thoroughly initially, and after some more testing it seems to work perfectly.
