### ISSUE TITLE
Qubes 4.1 - "unsupported qrexec version 3"

### ISSUE THREAD

**Issue by faerbersteve** [mirage/qubes-mirage-firewall#124]
In the log file guest-mirage-firewall is the line:
WRN qubes.rexec Error setting up vchan (domain..): (Failure "Unsupported qrexec version 3")

The mirage firewall is still working beside this warning. 

Is someone working on this?
Whag needs to be changed?

**Comment by talex5** [comment]
Looks like it's something to do with Qubes 4.1:

https://github.com/QubesOS/qubes-core-qrexec/commit/19b01423156e83ee841a5f422b56a6ced8710ec9

I don't know what changed in the protocol - anyone know?

**Comment by hannesm** [comment]
According to @reynir in https://github.com/mirage/mirage-qubes/issues/38 the qubes issue is https://github.com/QubesOS/qubes-issues/issues/4909

**Comment by ossii79** [comment]
@faerbersteve you running dom0 update via guest-mirage-firewall?
I just switched to mirage-firewall just to discover that I'm no longer able to update dom0 using a mirage-firewall as netvm.
Changing to sys-net or the stock sys-firewall then update works right away.

Console of the mirage-firewall reports "stub_gnttab_map_fresh: failed to map grant ref" and then "Unsupported qrexec version 3".

**Comment by faerbersteve** [comment]
@ossii79 I am using sys-net.
mirage-firewall can't be used as update vm.

**Comment by 0spinboson** [comment]
I'm getting a different error with Q4.1, using a newly built package. "client connected, using protocol version 3"
Solo5: trap: type=#MF ec=0x0 rip=0x28e5ee rsp=0x3ffd610 rflags=0x10293
abort cpu_x86_64.c:181: fatal trap.

**Comment by talex5** [comment]
Should be fixed by https://github.com/mirage/mirage-qubes/pull/56 (just negotiate to use the old version 2 instead of aborting).
