### ISSUE TITLE
qubes-mf not shutdown

### ISSUE THREAD

**Issue by Jiw0cha** [mirage/qubes-mirage-firewall#126]
Hello.
Qubes  4.0
Domain mirage-firewall with netvm -> sys-net.
sys-net add kernel_opts ```ipv6.disable=1```
All domain with netvm mirage-firewall fails start. And mirage-firewall infinity shutdown. (no shutdown, only kill)

**Comment by hannesm** [comment]
Dear @Jiw0cha, thanks for your report. Does the problem persist with qubes-mirage-firewall 0.8.2? Does the firewall start nicely (would you mind to attach the log if not)? Please reopen this issue once you tested the latest release.
