### ISSUE TITLE
Windows Xen PV Driver XENVIF fails to to install FrontendSetMaxQueues: device/vif/0:4

### ISSUE THREAD

**Issue by djeraseit** [mirage/qubes-mirage-firewall#127]
Qubes 4.0 (RC 4.0)
Xen version 4.8.5-25.fc25
Linux 4.19.155-1.pvops.qubes.x86_64

Guest: Windows Server 2019 Std

Using latest development master driver from https://xenbits.xen.org/pvdrivers/win
Output from `sudo xl console -t pv <vm-name>` 

Freezes on `xenvif|FrontendSetMaxQueues: device/vif/0:4`

Fix is to chose sys-firewall for NetVM.

[![xenvif.png](https://i.postimg.cc/TwQWkstj/xenvif.png)](https://postimg.cc/Vrr6vKQ5)

[![fw.png](https://i.postimg.cc/VkM0yv7k/fw.png)](https://postimg.cc/K1G8BGS6)

**Comment by xaki23** [comment]
what version of mirage-firewall is this?
(or: is your mirage-firewall using "pv" or "pvh"?)

**Comment by hannesm** [comment]
Thanks for your issue report. Please re-open with additional information if the problem persists with qubes-firewall 0.8.2.
