### ISSUE TITLE
Qubes 4.1, fatal error 'solo5 fatal trap'

### ISSUE THREAD

**Issue by 0spinboson** [mirage/qubes-mirage-firewall#128]
I'm getting a different error with Q4.1, using a newly built package. Last three lines of gues-mirage-firewall.log: 
> INF [qubes.rexec] client connected, using protocol version 3
> Solo5: trap: type=#MF ec=0x0 rip=0x28e5ee rsp=0x3ffd610 rflags=0x10297
> abort cpu_x86_64.c:181: fatal trap.

**Comment by talex5** [comment]
I've made a PR #129 to update to the new version of mirage-qubes, which should fix it.

**Comment by 0spinboson** [comment]
thanks

**Comment by a-barinov** [comment]
> I've made a PR #129 to update to the new version of mirage-qubes, which should fix it.

With manster branch and latest Qubes 4.1 I get similar error:
INF [qubes.rexec] client connected, other end wants to use protocol version 3, continuing with version 2
Solo5: trap: type=#MF ec=0x0 rip=0x28bded rsp=0x3ffd600 rflags=0x10293
abort cpu_x86_64.c:181: fatal trap.
