### ISSUE TITLE
compile problems.

### ISSUE THREAD

**Issue by eric-blabla** [mirage/qubes-mirage-firewall#131]
I have trouble to install the latest version (under debian buster). I did install docker from github and used the build-with-docker script.  All downloads (docker, github) were done via whonix (tor). The build trial ends with

"SHA2 of build:   0991877acc49b1c55a57dfa50df157fab7cc6c2fce5727f605e64a0bc73d322e  qubes_firewall.xen
SHA2 last known: d68d2a8d2337b8c1a78995e1acbb4f72082076c73be45bf40dd6268c87b2353e
(hashes should match for released versions)"

Thank you for any help!  

P.S: Here is the installed docker version:
Client: Docker Engine - Community
 Version:           20.10.2
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        2291f61
 Built:             Mon Dec 28 16:17:34 2020
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.2
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       8891c58
  Built:            Mon Dec 28 16:15:28 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

**Comment by donob4n** [comment]
Interesting,  I built with fedora 32 using podman instead docker and get the same checksum:
```
tar cjf mirage-firewall.tar.bz2 -C _build --mtime=./build-with-docker.sh mirage-firewall
SHA2 of build:   0991877acc49b1c55a57dfa50df157fab7cc6c2fce5727f605e64a0bc73d322e  qubes_firewall.xen
SHA2 last known: d68d2a8d2337b8c1a78995e1acbb4f72082076c73be45bf40dd6268c87b2353e

```

**Comment by h01ger** [comment]
On Wed, Feb 24, 2021 at 04:46:00AM -0800, donob4n wrote:
> Interesting,  I built with fedora 32 using podman instead docker and get the same checksum:

neat!


-- 
cheers,
	Holger

 ⢀⣴⠾⠻⢶⣦⠀
 ⣾⠁⢠⠒⠀⣿⡁       holger@(debian|reproducible-builds|layer-acht).org
 ⢿⡄⠘⠷⠚⠋⠀ PGP fingerprint: B8BF 5413 7B09 D35C F026 FE9D 091A B856 069A AA1C
 ⠈⠳⣄

**Comment by eric-blabla** [comment]
That is funny. I deleted everything & reinstalled everything (debian-10). It ends the same. Short version: youd someone comapre the intermediate hashes ??

er@mirage-builder:~/qubes-mirage-firewall$ sudo ./build-with-docker.sh 
Building Docker image with dependencies..
Sending build context to Docker daemon  200.7kB
Step 1/8 : FROM ocurrent/opam@sha256:fce44a073ff874166b51c33a4e37782286d48dbba1b5aa43563a0dd35d15510f
 ---> 451c7ddb25a3
Step 2/8 : RUN cd ~/opam-repository && git fetch origin master && git reset --hard 0531bd9f8068f9cbd0815cfc5fcbd6b6568e9620 && opam update
 ---> Using cache
 ---> d0868a6ca085
Step 3/8 : RUN opam depext -i -y mirage
 ---> Using cache
 ---> 98d550c9cd2c
Step 4/8 : RUN mkdir /home/opam/qubes-mirage-firewall
 ---> Using cache
 ---> d3ec368e147d
Step 5/8 : ADD config.ml /home/opam/qubes-mirage-firewall/config.ml
 ---> Using cache
 ---> fa127d3b0528
Step 6/8 : WORKDIR /home/opam/qubes-mirage-firewall
 ---> Using cache
 ---> 26fb59be0a4d
Step 7/8 : RUN opam config exec -- mirage configure -t xen && make depend
 ---> Using cache
 ---> ca2f22c3980a
Step 8/8 : CMD opam config exec -- mirage configure -t xen &&     opam config exec -- make tar
 ---> Using cache
 ---> 298b723db3cf
Successfully built 298b723db3cf
Successfully tagged qubes-mirage-firewall:latest
Building Firewall...
mirage build
rm -rf _build/mirage-firewall
mkdir _build/mirage-firewall
cp qubes_firewall.xen _build/mirage-firewall/vmlinuz
touch _build/mirage-firewall/modules.img
cat /dev/null | gzip -n > _build/mirage-firewall/initramfs
tar cjf mirage-firewall.tar.bz2 -C _build --mtime=./build-with-docker.sh mirage-firewall
SHA2 of build:   0991877acc49b1c55a57dfa50df157fab7cc6c2fce5727f605e64a0bc73d322e  qubes_firewall.xen
SHA2 last known: d68d2a8d2337b8c1a78995e1acbb4f72082076c73be45bf40dd6268c87b2353e
(hashes should match for released versions)

**Comment by hannesm** [comment]
fixed by merge of https://github.com/mirage/qubes-mirage-firewall/pull/140 -- please re-open (or open a new issue) if this is still a problem for you.
