### ISSUE TITLE
Consider using podman instead docker

### ISSUE THREAD

**Issue by donob4n** [mirage/qubes-mirage-firewall#132]
It seems that docker is getting abandoned in fedora in favor to podman so currently without passing some kernel args docker is even unusable in fedora-32.

I just tried installing it, 'sudo dnf install podman' and replacing 'docker' by 'podman' in 'build-with-docker.sh' and it worked!:

```
tar cjf mirage-firewall.tar.bz2 -C _build --mtime=./build-with-docker.sh mirage-firewall
SHA2 of build:   0991877acc49b1c55a57dfa50df157fab7cc6c2fce5727f605e64a0bc73d322e  qubes_firewall.xen
SHA2 last known: d68d2a8d2337b8c1a78995e1acbb4f72082076c73be45bf40dd6268c87b2353e

```
Notes:
- Run with sudo or it will fail due permissions errors
- Extend root partition or it ends due out of space.

**Comment by palainp** [comment]
Thanks for your suggestion, and sorry for the delay. I so far have no issues with docker and f37. Using podman is currently not planed.

**Comment by h01ger** [comment]
On Wed, Jul 05, 2023 at 10:11:04AM -0700, Pierre Alain wrote:
> Thanks for your suggestion, and sorry for the delay. I so far
> have no issues with docker and f37. Using podman is currently not planed.

sad face :(


-- 
cheers,
	Holger

 ⢀⣴⠾⠻⢶⣦⠀
 ⣾⠁⢠⠒⠀⣿⡁  holger@(debian|reproducible-builds|layer-acht).org
 ⢿⡄⠘⠷⠚⠋⠀  OpenPGP: B8BF54137B09D35CF026FE9D 091AB856069AAA1C
 ⠈⠳⣄

The law, in its majestic equality, forbids the rich as well as the poor to
sleep under bridges, to beg in the streets, and to steal bread. (Anatole France)

**Comment by hannesm** [comment]
I'm sure, now with "debian 12" and the packages from notset.fr being in use, this can be achieved easily. So, a PR `./build-with-podman.sh` (optimally reproducing the same hash) and a CI job that executes it would be very welcome. It is just our development resources on qubes-mirage-firewall won't cover to use podman, but we're happy to review pull requests that contribute it (and to avoid bitrot, the CI job is pretty important).

**Comment by h01ger** [comment]
On Thu, Jul 06, 2023 at 01:56:22AM -0700, Hannes Mehnert wrote:
> I'm sure, now with "debian 12" and the packages from notset.fr being in use,
> this can be achieved easily.

sadly snapshot.notset.fr is down (and will not come back) and
snapshot.reproducible-builds.org is not yet up. :/


-- 
cheers,
	Holger

 ⢀⣴⠾⠻⢶⣦⠀
 ⣾⠁⢠⠒⠀⣿⡁  holger@(debian|reproducible-builds|layer-acht).org
 ⢿⡄⠘⠷⠚⠋⠀  OpenPGP: B8BF54137B09D35CF026FE9D 091AB856069AAA1C
 ⠈⠳⣄

🔥 - this is fine.
