### ISSUE TITLE
Invalid kernel on Qubes 4.1.

### ISSUE THREAD

**Issue by MaxHillebrand** [mirage/qubes-mirage-firewall#138]
After following [instalation instructions](https://github.com/mirage/qubes-mirage-firewall#deploy) on Qubes 4.1, `qvm-start mirage-firewall` fails with:

```
xc: panic: xc_dom_elfloader.c:64: xc_dom_guest_type: image not capable of booting inside a HVM container: Invalid kernel
libxl: libxl_dom.c:578:libxl__build_dom: xc_dom_parse_image failed
libxl: libxl_create.c:1623:domcreate_rebuild_done: Domain 80:cannot (re-)build domain: -3
```

Maybe this is related? 

> All the files besides vmlinuz are optional in Qubes R4.1 or newer. In Qubes R4.0, vmlinuz and initramfs are both required to be present.
https://www.qubes-os.org/doc/managing-vm-kernels/#kernel-files-structure

But when removing `initramfs`, `qvm-create ...` fails with:
```
app: Error setting property kernel (but VM created): Kernel 'mirage-firewall' not properly installed: missing 'initramfs' file
```

**Comment by Szewcson** [comment]
You should set VM as PV not HVM - check in readme.

**Comment by palainp** [comment]
With the latest update, the command lines for creating the AppVM should be clearer.
Can you try to recreate your firewall-vm with the new directives?
