### ISSUE TITLE
Is there a GUI for firewall rules for this?

### ISSUE THREAD

**Issue by PowerPress** [mirage/qubes-mirage-firewall#148]
Is there a GUI for firewall rules for this?

**Comment by hannesm** [comment]
Hi, I'm not sure I understand your question. The firewall rules configured in QubesDB (see https://www.qubes-os.org/doc/firewall/) are used by this firewall. Thus there is no graphical user interface, but the standard Qubes firewall rule interface applies.

Please reopen if you had a different question in mind.
