### ISSUE TITLE
IP checksums

### ISSUE THREAD

**Issue by hannesm** [mirage/qubes-mirage-firewall#153]
From the #OCaml IRC channel, it may be worth to just drop any IP checksum computations (IPv6 doesn't have checksums anyways, and most of the IPv4 checksums on the Internet are wrong). This may help in respect to speedups.

**Comment by haesbaert** [comment]
I don't see why, I also never heard about having wrong checksums in the
wild. OpenBSD stack just drops on bad checksum, and I assume all other as
well.

**Comment by hannesm** [comment]
Yes, @haesbaert -- likely you're right, I still think we should take a look into the bottlenecks, and checksum code is C and could benefit from a check whether this is the hot path...

**Comment by haesbaert** [comment]
Ack, just have in mind that the IP checksum is nothing compared to the TCP one, since it's just the header, and in my humble experience (at least on a BSD stack), the cycles for checksuming are not significant.

**Comment by hannesm** [comment]
Let's close this, performance evaluation is important, but best not be done on a speculative basis. So, better to benchmark and figure out numbers before trying to propose fixes.
