### ISSUE TITLE
Detach netvm fails for mirage v0.8.2

### ISSUE THREAD

**Issue by rootnoob** [mirage/qubes-mirage-firewall#157]
Attempting to detach mirage-firewall (v0.8.2) as netvm fails, and leaves the vm without a network connection - unable to change the netvm.

1) qvm-prefs VM netvm mirage-firewall
2) qvm-prefs VM netvm x
error: no such property 'netvm'
2) qvm-prefs VM
netvm: mirage-firewall

journalctl shows issue with netvm detach.

VM has no network connection

Other VMs can still be attached to mirage-firewall, so its just an issue with detaching from mirage.

Submitting this issue here as only encountered this with mirage.

**Comment by palainp** [comment]
I just pushed a PR on mirage-net-xen that allows to dynamically change the netvm for any client VM without `qvm-prefs: error: no such property: 'netvm'` anymore.

**Comment by hannesm** [comment]
Thanks for your report, this has been fixed in the 0.8.3 release. Please re-open if it still fails for you.
