### ISSUE TITLE
how to use / configure this?

### ISSUE THREAD

**Issue by h01ger** [mirage/qubes-mirage-firewall#18]
is this firewall configured exactly the same way as the "original" QubesOS one?

how does one configure the rules this one? are there any files which (for normal usage) can be edited besides rules.ml?

would you accept patches for README.md clarifying these questions? or would you prefer some other new file?

**Comment by talex5** [comment]
The README currently says:

> Note: This firewall ignores the rules set in the Qubes GUI. See rules.ml for the actual policy.

This should be the only file that needs changing, but of course you might find a limitation of the firewall and need to extend the rules. Hopefully such extensions can be merged back here.

Qubes gives the firewall rules to the firewall as Linux iptables commands, which isn't very useful to us. There were some plans to change that, but I don't know what the outcome was:

https://groups.google.com/d/msg/qubes-devel/kvbKXT5CJMU/rSMD6Je3BgAJ

There is some documentation in the `rules.ml`, but feel free to clarify it. One thing that might be useful: replacing the polymophic variants with plain ones (e.g. `` `Nat`` -> `Nat`). That might give clearer error messages if the user makes a mistake.

**Comment by h01ger** [comment]
I tried to modify rules.ml to allow connections from template VMs to 10.137.255.254, tcp, port 8082, but I didn't understand how. Could you please clarify how to achieve this, either by names or ip or mac addresses?

**Comment by h01ger** [comment]
btw, you might also want to read http://layer-acht.org/thinking/blog/20171204-qubes-mirage-firewall/ - I'll post a link to the qubes-user list once the event here is over and I learned some more.

also: many thanks for qubes-mirage-firewall, I"m quite very happy with it already!

**Comment by talex5** [comment]
Connections from template VMs should already be allowed by the default rules.

It would be nice to restrict templates to using *just* the update servers, though.

I think you can get the IP with something like:

```
| { src = `Client iface } when is_template iface#other_ip -> ...
```

But you have to write `is_template` yourself. It would be nice if the firewall could classify the VMs for you, or tag them with their names. Then you could do e.g.

```
| { src = `Client { name = "fedora-26-template" } } -> ...
```

Unfortunately, I don't think that Qubes provides this information to the firewall.

**Comment by h01ger** [comment]
On Mon, Dec 04, 2017 at 04:48:26PM +0000, Thomas Leonard wrote:
> Connections from template VMs should already be allowed by the default rules.

not to 10.137.255.254, which is sys-net, serving as update-proxy for the
template VM. this is prohibited by the default VMs.

  | { dst = `Client _ } -> `Drop "prevent communication between client VMs"

is the line preventing it :)

> It would be nice to restrict templates to using *just* the update servers, though.

see above.

> I think you can get the IP with something like:
> 
> ```
> | { src = `Client iface } when is_template iface#other_ip -> ...
> ```
> 
> But you have to write `is_template` yourself. It would be nice if the firewall could classify the VMs for you, or tag them with their names. Then you could do e.g.
> 
> ```
> | { src = `Client { name = "fedora-26-template" } } -> ...
> ```
> 
> Unfortunately, I don't think that Qubes provides this information to the firewall.

TBH, I currently cannot see how this can be usable out of the box / with one
rules.ml file for every default QubesOS user :/

So, for now the solution is to use the default sys-firewall for Template
VMs?! I can come up with a patch for README.md for that ;) 

Plus I think there should be one example for eg allowing the "personal"
VM access port 80 on the "work" VM. (And/or for 10.137.42.42 accessing
Port 80 on 10.137.23.23, as said: I couldnt figure out the syntax for
that...)


-- 
cheers,
	Holger

**Comment by h01ger** [comment]
(and regarding your first reply: I think the README.md should describe what rules.ml does (briefly and in words, not in code), IOW: what firewall features qubes-mirage-firewall.git provides. I"ll try to come up with a patch eventually, it"s probabl 2-3 sentences.)

**Comment by talex5** [comment]
Have you tested updating a template VM and found it doesn't work? It works for me. The rule that matches `sys-net` should be this one, assuming `sys-net` is the firewall's NetVM:

```
| { dst = (`External _ | `NetVM) } -> `NAT
```

**Comment by h01ger** [comment]
On Mon, Dec 04, 2017 at 05:06:03PM +0000, Thomas Leonard wrote:
> Have you tested updating a template VM and found it doesn't work? It works for me. 

hah! qubes-updates-proxy in sys-net once again crashed, and after a
restart of that service I could indeed communication with the update
proxy from the template VM. Nice. (And apologies, I anticipated uplink
problems here, but didnt think of other qubes issues causing
problems...)

I've also updated my blog post now to clarify this.

> The rule that matches `sys-net` should be this one, assuming `sys-net` is the firewall's NetVM:
> 
> ```
> | { dst = (`External _ | `NetVM) } -> `NAT
> ```

of course you are right. Thanks for bearing with me!

however, I still wonder how I allow 10.137.42.42 to access 10.137.23.23
on port 80 :)


-- 
cheers,
	Holger

**Comment by talex5** [comment]
> however, I still wonder how I allow 10.137.42.42 to access 10.137.23.23 on port 80 :)

Assuming .42 is a client VM, .23 is NetVM, and you want TCP port 80, something like this should work:

```
let client_addr = Ipaddr.V4.of_string_exn "10.137.42.42"

let from_client = function
  | { src = `Client c; dst = `NetVM; proto = `TCP { dport = 80 } } when c#other_ip = client_addr -> `NAT
  ...
```

**Comment by h01ger** [comment]
On Mon, Dec 04, 2017 at 07:56:20PM +0000, Thomas Leonard wrote:
> > however, I still wonder how I allow 10.137.42.42 to access 10.137.23.23 on port 80 :)
> Assuming .42 is a client VM, .23 is NetVM, and you want TCP port 80, something like this should work:

cool, many thanks! and if .23 is a client VM to, I just replace that
string... (just double checking cause I basically have 0 ocaml
experience...)

>   | { src = `Client c; dst = `NetVM; proto = `TCP { dport = 80 } } when c#other_ip = client_addr -> `NAT

I also plan to come up with a nice patch for this issue now! Thanks
again!


-- 
cheers,
	Holger

**Comment by talex5** [comment]
If they're both clients, you have to match both IP addresses, e.g.

```ocaml
 | { src = `Client cs; dst = `Client cd; proto = `TCP { dport = 80 } }
    when cs#other_ip = src_client_addr
      && cd#other_ip = dst_client_addr
```

**Comment by h01ger** [comment]
On Thu, Dec 07, 2017 at 02:39:28AM -0800, Thomas Leonard wrote:
> If they're both clients, you have to match both IP addresses, e.g.

thanks, that should give me enough information to come up with a patch
documenting this. Now I just need the time…


-- 
cheers,
	Holger
