### ISSUE TITLE
Memory issues with Qubes 4.2

### ISSUE THREAD

**Issue by palainp** [mirage/qubes-mirage-firewall#182]
Reported by @51lieal in #181 and xprimv in https://forum.qubes-os.org/t/mirage-firewall-breaks-connectivity-daily/20400 . Qubes-mirage-firewall have troubles pretty soon in a Qubes 4.2 environment.

I'll investigate what's going on as soon as possible (tm) when Qubes 4.2 will be out.

/cc @hannesm @xaki23

**Comment by palainp** [comment]
@51lieal , just to rule out an issue about the meminfo key in xenstore. Can you confirm that your mirage-fw VM have "include in memory ballooning" unchecked?

And if you want and can compile a local mirage-fw version, would you mind to try https://github.com/palainp/qubes-mirage-firewall/tree/fix-4.2 that rolback the meminfo write to the maxmem value (I hope it'll indicate to Xen to leave us out memory)?

**Comment by 51lieal** [comment]
Unfortunately, nope. I am currently in the process of rebuilding with some modifications to collect log information. As anticipated, the logs are generating multiple entries with messages such as 'memory pressure alleviated' and 'memory is critically low.

I'll try to fix it and sent pr when done.

**Comment by palainp** [comment]
So far I do not observe any memory/network issue with 32M after 24h+ even after putting Qubes under memory pressure.

**Comment by palainp** [comment]
Closed with #189
