### ISSUE TITLE
Inform the necessary space required to build the unikernel

### ISSUE THREAD

**Issue by ben-grande** [mirage/qubes-mirage-firewall#186]
## Problem

I noticed when building that docker overlays got close to 6GB and after the build it regressed. I know it is less than 10GB, which is what a normal qube has as the private volume, but it would be good if informed in case the user has already some data on the build qube.
I don't know a good way to measure, I was just using `sudo du -h /var/lib/docker` during the build.

## Request

Can you please inform in the README the necessary space, not based on what I said above... I should have monitored better, but based on the your local tests.

**Comment by palainp** [comment]
Thanks for this comment, you mean rising e.g from 4096MiB to 8192MiB in https://github.com/mirage/qubes-mirage-firewall#build-from-source ?

**Comment by palainp** [comment]
I can confirm it goes up to 5.9GiB when it comes to install solo5. I'll push another commit into README.md :+1/

**Comment by ben-grande** [comment]
> Thanks for this comment, you mean rising e.g from 4096MiB to 8192MiB in https://github.com/mirage/qubes-mirage-firewall#build-from-source ?

Yes.

> I can confirm it goes up to 5.9GiB when it comes to install solo5. I'll push another commit into README.md :+1/

Thank you.

**Comment by palainp** [comment]
Thanks, fixed in #185.
