### ISSUE TITLE
SaltScript breaks with 0.9.0

### ISSUE THREAD

**Issue by ideologysec** [mirage/qubes-mirage-firewall#195]
It seems like there's a parsing error in the command-line invocations, since the checksums do match but the stdout seems to indicate that extra characters are being added in for the string compare - I've tried to unmarshal the cut + tr commands but there's so many escape characters I haven't had any luck yet.

![image](https://github.com/mirage/qubes-mirage-firewall/assets/790061/f4a79553-f5d2-4343-a6bb-35c7050f1e8c)

**Comment by palainp** [comment]
Thank you for the report @ideologysec, it should be fixed now.
