### ISSUE TITLE
compilation issue with mirage 4.5.1

### ISSUE THREAD

**Issue by hannesm** [mirage/qubes-mirage-firewall#196]
```
471.326s:# File "dispatcher.ml", line 3, characters 17-29:
471.326s:# 3 | module Netback = Backend.Make (Xenstore.Make (Xen_os.Xs))
471.326s:#                      ^^^^^^^^^^^^
471.326s:# Error: Unbound module Backend.Make
```

The underlying problem as far as I can tell is that mirage-bootvar defines a module `Backend` (and is not wrapped), and also mirage-net-xen is not wrapped and defines a module Backend. I'll work on fixing mirage-bootvar and cut a release.

**Comment by hannesm** [comment]
fixed by https://github.com/ocaml/opam-repository/pull/25909 when merged to the repository. I'll close this issue.

**Comment by palainp** [comment]
Thank you @hannesm! Do you think that wrapping `Backend` in mirage-net-xen should be done too? That might break code in other places.
