### ISSUE TITLE
crashed with out of memory 

### ISSUE THREAD

**Issue by h01ger** [mirage/qubes-mirage-firewall#20]
after just 2-3 days of uptime today I could see this in the mirage-firewall console:

-----
2017-12-08 01:47:08 -00:00: INF [client_eth] responding to: who-has 10.137.7.1?
Fatal error: out of memory.
Mirage exiting with status 2
Do_exit called!
-----

and no mirage-firewall running in the system anymore and qubes/libxen in an incosistent state, so I couldnt jhust restart it again but had to restart the whole system...

this happended while sys-net was (physically) disconnected from everything, so there was no network traffic at all. (so there is probably a lot of time between the first and second line in the above log.) mirage-firewall is running with 32mb of memory and normally using 10-15mb of it.

my mirage-firewall was build upon commit aca156f21b8e2 (so latest commit from november 14 2017) as described in my blogpost. I'd be glad to build another image with some more debug output or some such.

**Comment by talex5** [comment]
The exact amount of memory it needs depends on the number of client VMs - you might need to increase it slightly if you have many.

It would be nice to handle this better, though. Whenever I've seen this, there was plenty of free RAM and then suddenly an OOM. It might be worth adding a printk to mini-os's malloc (try reverting this commit: https://github.com/talex5/mini-os/commit/e4802ffec913af27ac386a1f18ee6fb7a500d308). The amount of memory it's trying to allocate might be a clue about where it's coming from.

**Comment by h01ger** [comment]
On Sat, Dec 09, 2017 at 11:43:51AM +0000, Thomas Leonard wrote:
> The exact amount of memory it needs depends on the number of client VMs - you might need to increase it slightly if you have many.

I dont have many VMs running, at the time of the crash there were maybe
10, on a 16gb machine with 6gb used for real, and mirage-firewall
configured to use 32mb. And there was no network traffic (possible),
neither. I'm starting to suspect that the latter might be causing this
somehow…

> It would be nice to handle this better, though.

Yes!

>Whenever I've seen this, there was plenty of free RAM and then suddenly an OOM. It might be worth adding a printk to mini-os's malloc (try reverting this commit: https://github.com/talex5/mini-os/commit/e4802ffec913af27ac386a1f18ee6fb7a500d308). 

I fear I currently still lack the opam skills to do that…

If you could point me in the right direction how to do that, or give
manual pointers… sorry, I'm a total ocaml+opam+mirage newbee! :)

> The amount of memory it's trying to allocate might be a clue about where it's coming from.

*nods*, thanks!


-- 
cheers,
	Holger

**Comment by talex5** [comment]
It's possible that if netvm isn't delivering frames then they might queue up. But there's supposed to be a limit to that.

Testing mini-os modifications should be something like:

```
git clone https://github.com/talex5/mini-os.git
cd mini-os
[ edit mm.c/alloc_pages/no_memory as desired ]
opam pin add -k git minios-xen .
```

That will rebuild all the Mirage xen libraries. Then `make clean` and rebuild your unikernel.

You might be able to make `alloc_pages` call `stack_walk()` on error too, to get a stack-trace.

**Comment by talex5** [comment]
Haven't seen any OOM errors for a long time. Please reopen if it's still happening with the latest version.
