### ISSUE TITLE
missing field license

### ISSUE THREAD

**Issue by palainp** [mirage/qubes-mirage-firewall#206]
In github actions I can see:
```
Warning:  Failed checks on qubes-firewall-xen package definition from source at file:///tmp/orb-build/mirage:
           warning 68: Missing field 'license'
```
I don't know where this field is missing, and it doesn't prevent the unikernel from being built, but if anyone has an idea, it would be welcome :)

**Comment by hannesm** [comment]
Well spotted, I suspect the path to get there is to propose a license (maybe MIT), and ask all contributors with substantial changes to agree to that license.

**Comment by hannesm** [comment]
see #207, let's see how it goes :)

**Comment by palainp** [comment]
Thank you :heart: !
