### ISSUE TITLE
HVM support 

### ISSUE THREAD

**Issue by setsky** [mirage/qubes-mirage-firewall#29]
Dear @talex5, many thanks for your work with awesome firewall!

1. I can't start the firewall in HVM mode in QubesOS, do you plan to introduce support for this mode?

2. Also I have another question, don't want create more tickets. It's not really issue but...
I have attached three appVMs to one miragefirewallVM
So considering that I'm using a standard setup of firewall (your binary files from the github), can appvm1 communicate with appvm2 or appvm3? Or are all machines strictly isolated from each other?

**Comment by yomimono** [comment]
Hi @setsky, I'm not @talex5 but I think I can answer your questions (and I think it's fine to create more than one issue when you have more than one question :) ).

(1) - HVM support for qubes-mirage-firewall depends on HVM support for Xen in MirageOS generally, which has been <a href="https://github.com/mirage/mirage/issues/313">an outstanding issue for some time</a>.  After discussing this in March, I intend to do <a href="https://github.com/mirage/mirage-platform/issues/199">some work on it</a> this month.  If you subscribe to either of the issues linked above, you'll get notifications when we update those tickets to indicate our progress, which `qubes-mirage-firewall` will eventually inherit.

(2) - [by default](https://github.com/talex5/qubes-mirage-firewall/blob/master/rules.ml#L34), clients are not allowed to communicate with one another across the firewall.

**Comment by setsky** [comment]
@yomimono Many thanks! ;) Got it!

**Comment by hannesm** [comment]
2.5 years later, thanks to @mato MirageOS 3.9.0 finally supports PVH (see https://github.com/mirage/mirage/issues/1159 for details, as well #116). Also thanks to previous efforts on that front by @marmarek and @yomimono.

**Comment by samoht** [comment]
Hey @setsky! 4 years later I am wondering if you would be happy to discuss your usage of the MirageOS firewall. We are very interested to get user feedback (positive and negative)!
