### ISSUE TITLE
icmp truncated payload support

### ISSUE THREAD

**Issue by xaki23** [mirage/qubes-mirage-firewall#31]
2018-10-03 03:22:53 -00:00: WRN [uplink] Ignored unknown IPv4 message from uplink: Failed to parse ICMP error's payload: Payload buffer (528 bytes) too small to contain payload (of size 1472 from header)

thats normal for certain kinds of icmp where a truncated part of the triggering pkt is included for reference.
dropping these pkts on the floor breaks pmtu discovery for downstream VMs. 
the truncation should just be ignored and the payload header parsed for de-nat purposes.

**Comment by hannesm** [comment]
FWIW, related is support for reassembly of mirage-tcpip at https://github.com/mirage/mirage-tcpip/pull/375 which could once merged be used as a basis for support in here

**Comment by talex5** [comment]
The error is from mirage-nat:

https://github.com/mirage/mirage-nat/blob/master/lib/nat_packet.ml#L65

It seems to be expecting tcpip to return as much of the payload as is available, but tcpip (correctly, I think) rejects the packet. Maybe we should modify the length field before passing it to the parser?

**Comment by yomimono** [comment]
[This PR to `mirage-tcpip`](https://github.com/mirage/mirage-tcpip/pull/397), if merged, will help `mirage-nat` do the right thing in this case.

**Comment by yomimono** [comment]
[PR for `mirage-nat`](https://github.com/mirage/mirage-nat/pull/26).

**Comment by xaki23** [comment]
since i am unsure how to testbuild the change while its still a PR ... (guess: opam pin to the PR repo url?)
... a minimal setup for triggering this:

netvm (sys-net) -- mirage-fw -- appvm

in netvm: iptables -I FORWARD -p icmp -m dscp --dscp-class BE -j REJECT
in appvm: ping -s 1000 -Q 0xbe 1.2.3.4

**Comment by yomimono** [comment]
This patch seems to properly pass ICMP error messages embedding TCP and UDP packets, but not ICMP echo requests, so the above test fails (whereas setting a firewall rule that rejects traffic on TCP port 443 generates ICMP errors that the appvm receives in response to `wget`).

**Comment by yomimono** [comment]
Actually, ICMP was straight-up broken in the latest release (not the firewall's fault, but the new code path exposes a bug in `tcpip`'s ICMP checksum calculation).  Building against https://github.com/mirage/mirage-tcpip/pull/401 helps but `tracepath` continues to give weird results, so there's at least one thing that's still not handled correctly; I'll keep digging.

**Comment by xaki23** [comment]
the three-pins-and-working state at https://github.com/mirage/mirage-nat/pull/26#issuecomment-482944176 fixes this particular issue afaict.
since none of the three pins/changes are against mirage-firewall, i am going to close this issue.
