### ISSUE TITLE
Changing Guest NetVM property breaks it until reboot

### ISSUE THREAD

**Issue by dakka2** [mirage/qubes-mirage-firewall#59]
If the netvm property of a guest is changed rather then shutting it down first before changing it the netvm property becomes broken until the guest is restarted. mirage is unable to remove a guest vif that is only removed and not just shutting down. this error is printed: 
`WRN [net-xen:xenstore] Error reading device state at "/local/domain/88/device/vif/0": Xs_protocol.Error("EACCES")`
`INF [net-xen:backend] Frontend asked to close network device dom:88/vif:0`
`INF [client_net] client {domid=88;device_id=0} has gone`

qvm-prefs (if using it to set the netvm property on the guest) returns "no property netvm" and refuses to set a new netvm property after that.

**Comment by dakka2** [comment]
in addition it appears the upstream netvm of mirage-firewall also appears to also not be hotpluggable.

**Comment by talex5** [comment]
Removing it manually, I see:

```
[tal@dom0 ~]$ xl -vvv network-detach test 0
libxl: debug: libxl_nic.c:556:libxl_device_nic_remove: ao 0x1506cf0: create: how=(nil) callback=(nil) poller=0x1507550
libxl: debug: libxl_event.c:636:libxl__ev_xswatch_register: watch w=0x1507240 wpath=/local/domain/133/backend/vif/136/0/state token=3/0: register slotnum=3
libxl: debug: libxl_nic.c:556:libxl_device_nic_remove: ao 0x1506cf0: inprogress: poller=0x1507550, flags=i
libxl: debug: libxl_event.c:573:watchfd_callback: watch w=0x1507240 wpath=/local/domain/133/backend/vif/136/0/state token=3/0: event epath=/local/domain/133/backend/vif/136/0/state
libxl: debug: libxl_event.c:878:devstate_callback: backend /local/domain/133/backend/vif/136/0/state wanted state 6 still waiting state 5
libxl: debug: libxl_event.c:573:watchfd_callback: watch w=0x1507240 wpath=/local/domain/133/backend/vif/136/0/state token=3/0: event epath=/local/domain/133/backend/vif/136/0/state
libxl: debug: libxl_event.c:867:devstate_callback: backend /local/domain/133/backend/vif/136/0/state wanted state 6 but it was removed
[...]
```

So, it looks like it wants us to move the `Closed` state (6) rather than deleting the backend directory. 

However, mirage-net-xen (https://github.com/mirage/mirage-net-xen/blob/d46a0a0cda2ae2f550b6a36ce591ee92616984af/lib/xenstore.ml#L322) refers to https://github.com/mirage/xen/commit/546678c6a60f64fb186640460dfa69a837c8fba5, which says

> Fix this by making sure the control domain only cleans the frontend path,
leaving the backend path to be cleaned by the driver domain.

Which seems to suggest that we should be deleting it.

**Comment by hannesm** [comment]
According to git log, with mirage-net-xen 1.12.0 (released 2019-06-26), part of the latest binary release of the qubes firewall (0.7), this issue shouldn't be present anymore.

I'll close it, please feel free to reopen it. Also, expect soon a new binary release. Thanks for your report.

**Comment by rootnoob** [comment]
This issue has re-appeared in v0.8.2
https://github.com/mirage/qubes-mirage-firewall/issues/156
https://github.com/mirage/qubes-mirage-firewall/issues/157
