### ISSUE TITLE
Remove dummy kernel files

### ISSUE THREAD

**Issue by talex5** [mirage/qubes-mirage-firewall#70]
The mirage-firewall distribution includes dummy `modules.img` and `initramfs` files. These were needed on Qubes 3 for it to accept something as a kernel.

On Qubes 4 (according to https://www.qubes-os.org/doc/managing-vm-kernel/):

> All the files besides vmlinuz are optional.

We should remove these dummy files from the build and installation instructions.

**Comment by marmot1791** [comment]
As of today on Qubes R4.0 with all updates dom0 still requires the dummy initramfs to start a mirage qube, but modules.img is not required.

**Comment by marmot1791** [comment]
Opened question of whether this is a bug or a docs issue over at qubes-issues: https://github.com/QubesOS/qubes-issues/issues/5516

**Comment by marmot1791** [comment]
This is partially blocked until Qubes R4.1. Until that is released `initramfs` is still required.

**Comment by hannesm** [comment]
Since Qubes 4.0 is end of life now, IMHO it would be good to remove the initramfs file. This also means that our packaging and install instructions can be much simpler (we'll only distribute a single binary, and no need for `tar`).

Does this make sense @palainp?

**Comment by palainp** [comment]
This should be right according to the documentation, but I was unable to boot without it some times algo :/

**Comment by palainp** [comment]
This is still the case, I have the following:
```
Missing file: /var/lib/qubes/vm-kernels/mirage-fw/initramfs
```

**Comment by palainp** [comment]
The existence of initramfs is checked in https://github.com/QubesOS/qubes-core-admin/blob/c177aacbe1afc35034826ef538c0e49ed40b6bc7/qubes/storage/kernels.py#L140
See: https://github.com/QubesOS/qubes-issues/issues/5516

**Comment by hannesm** [comment]
Thanks @palainp for your investigations :)

**Comment by palainp** [comment]
https://github.com/QubesOS/qubes-issues/issues/5516 has been resolved now. This will works with the next Qubes update, and we can remove that dummy file for the next release :)
