### ISSUE TITLE
Busted install link?

### ISSUE THREAD

**Issue by chaywoo** [mirage/qubes-mirage-firewall#92]

**Comment by chaywoo** [comment]
git clone https://github.com/mirage/qubes-mirage-firewall.git is busted 'Could not resolve host: Github.com' trying to install mirage-firewall-qubes but this is where everything came to a screeching halt.

**Comment by xaki23** [comment]
sounds like a network problem of the buildvm.
does "ping 8.8.8.8" work in that buildvm?
if whonix/tor is involved in the nonworking attempt, does it work when using plainnnet?

**Comment by talex5** [comment]
Also, if you're building on Docker, what version? Distribution-provided versions are sometimes broken, so try one from docker.com (though Fedora's one worked last time I checked). To test it, try:

```bash
$ sudo docker run --rm -it ocurrent/opam:alpine-3.10-ocaml-4.08 sudo ping github.com
PING github.com (140.82.118.4): 56 data bytes
64 bytes from 140.82.118.4: seq=0 ttl=50 time=39.310 ms
...
```

**Comment by chaywoo** [comment]
Hey thanks so much for the comments. I did ping 8.8.8.8 and that did work.. 
After running the $ sudo command I got this response..
/usr/bin/docker-current: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?.
See '/usr/bin/docker-current run --help'.
I got this same response from the terminal in fedora30 templatevm and the build appvm.
ping github works only when the fadora30 template is running and there is a "vm uplink eth0 active" networking icon in the little icon box.
I will go back and read the directions again, it looks like it says the docker version is 'current'?
Thanks so much for the comments, I think the mirage firewall in qubes is brilliant and I cant wait to use it..

**Comment by chaywoo** [comment]
oops, no ping github does not work from buildvm and it says Namr or service not known in the fedora-30 vm template terminal.. oops,

**Comment by xaki23** [comment]
yes, template vms do not have networking by default.
i am also not sure how a template vm got involved in the build process here. 
i suggest we close this for now and reopen if the problem persists and more details become avail.

**Comment by talex5** [comment]
Yeah, if you can't ping github from your build AppVM using the regular sys-firewall then the problem certainly isn't with mirage-firewall.

**Comment by chaywoo** [comment]
Yeah,  github ping was no problem, it was the particular recommended location within github that wasn't responding. It's been a while now and I couldn't find any info so I let that one rest. I think such an install in my opinion is for high experienced qubes users. I managed to set up bionic desktop, ubuntu, and a very isolated windows 10 making it useless without something like the mirage firewall.  I have networked equipment that can't communicate with windows 10 that's why I tried the mirage firewall. Maybe I will try again this June when I have a little extra time, thanks for the pointerSent from my T-Mobile 4G LTE Device
-------- Original message --------From: Thomas Leonard <notifications@github.com> Date: 3/22/20  4:31 AM  (GMT-08:00) To: mirage/qubes-mirage-firewall <qubes-mirage-firewall@noreply.github.com> Cc: Chris <chris@afso.us>, Author <author@noreply.github.com> Subject: Re: [mirage/qubes-mirage-firewall] Busted install link? (#92) 
Yeah, if you can't ping github from your build AppVM using the regular sys-firewall then the problem certainly isn't with mirage-firewall.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/mirage/qubes-mirage-firewall/issues/92#issuecomment-602185051",
"url": "https://github.com/mirage/qubes-mirage-firewall/issues/92#issuecomment-602185051",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
