### ISSUE TITLE
Mirage unikernel VPN support

### ISSUE THREAD

**Issue by ghost** [mirage/qubes-mirage-firewall#94]
Hi @talex5 and thank you!
Is there a Mirage Unikernel equivalent for VPNs?

**Comment by xaki23** [comment]
none i am aware of.
there are however various vpn-related protocols implemented in ocaml already.
so the main part missing is for someone to slap it together into a usable vm.

there may or may not be people planning to work on that at the 2020-03 retreat. 

ping @hannesm @laudecay

**Comment by tortugaverde98** [comment]
Is the 2020-03 retreat still on, even in a virtual format? I am anxiously awaiting a ocaml/mirage unikernel that reads OVPN files. Surely many other qubes users are, too.

**Comment by hannesm** [comment]
sorry, there has been not much happening on this front at the retreat AFAICT (there are other QubesOS-related news -- namely Xen-PVH, which we'll hopefully shortly get into MirageOS merged and released)

**Comment by ideologysec** [comment]
well, there's @roburio 's https://github.com/roburio/openvpn that also specifically mentions mirage-firewall, so, presumably this could get turned into a working mirage-vpn Qube at some point.

and there was apparently at one point an attempt at a wireguard-ocaml implementation (https://github.com/cfcs/ocaml-wireguard) which is now 404, but existed long enough to be [referenced here.](https://www.old.reddit.com/r/Qubes/comments/eosg40/is_there_a_mirage_unikernel_equivalent_for_vpns/)

**Comment by hannesm** [comment]
I'm closing this issue, it is unrelated to the qubes-mirage-firewall. For discussions about future VPN unikernels, let's talk on the mirage mailing list, or discuss.ocaml.org (or reach out to team at robur dot coop).

**Comment by dinosaure** [comment]
Just to inform you that [Robur](https://robur.coop) are currently developping a QubesOS unikernel as a VPN client. It is available here: https://github.com/robur-coop/qubes-miragevpn. A tutorial is actually available here too: https://github.com/robur-coop/miragevpn-handbook/pull/3
